server:
   port: 8061
info:
    component: Microservicio de back dominio catalogo
spring:
  application:
    name: msinme-ctalogo
  datasource:    
     url: jdbc:sqlserver://172.16.164.18\NSMISQL:1433;databaseName=ESMER;
     username: INME_USER
     password: 1Nm32020
  jpa:
     show-sql: true
     hibernate:
        ddl-auto: none
     properties:
        hibernate:
           dialect: org.hibernate.dialect.SQLServer2012Dialect
management:
 endpoints:
  web:
   exposure:
    include:  info, health